name: Docker Job Build

on:
  push:
    branches:
      - develop

env:
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_IMAGE_REPOSITORY: ${{secrets.AWS_IMAGE_REPOSITORY}}
  PROJECT_ENVIRONMENT: "development"
  PROJECT_IMAGE_DOCKERFILE: "Dockerfile"

jobs:
  docker-build:
    # if: ${{ false }} # Disable Job
    runs-on: ubuntu-20.04
    name: Ecs Build
    steps:
      - name: checkout code
        uses: actions/checkout@v2

#      - name: Copy files
#        run: cp -r backend/* ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build artifacts for project
        run: make docker-build-image

      - name: Push Image
        run: make docker-push-image

      - name: Deploy to Amazon ECS
        uses: ./
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          CLUSTER_NAME: tracking-development
          SERVICE_NAME: api
          DESIRED_COUNT: 1